routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes(['verify' => true]);

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::middleware('auth', 'verified')->group(function(){
	Route::get('master/category', 'CategoryController@index')->name('master.category');

	Route::resource('category', 'CategoryController')->scoped([
		'category' => 'slug',
	]);

	Route::get('news/all','NewsController@all')->name('news.all');
	Route::get('news/draft','NewsController@draft')->name('news.draft');
	Route::get('news/pending','NewsController@pending')->name('news.pending');
	Route::get('news/published','NewsController@published')->name('news.published');

	Route::patch('news/{news:slug}/edit', 'NewsController@update');
	Route::resource('news', 'NewsController')->scoped([
	    'news' => 'slug',
	]);

	Route::get('utility/menu', 'UtilityController@menu')->name('utility.menu_manage');

	Route::post('utility/savemenu1', 'UtilityController@savemenu1')->name('utility.saveMn1');
	Route::get('utility/editmenu1/{id}', 'UtilityController@editmenu1')->name('utility.editMn1');
	Route::post('utility/updatemenu1/{id}', 'UtilityController@updatemenu1')->name('utility.updateMn1');
	Route::get('utility/deletemenu1/{id}', 'UtilityController@deletemenu1')->name('utility.deleteMn1');

	Route::post('utility/savemenu2', 'UtilityController@savemenu2')->name('utility.saveMn2');
	Route::get('utility/editmenu2/{id}', 'UtilityController@editmenu2')->name('utility.editMn2');
	Route::post('utility/updatemenu2/{id}', 'UtilityController@updatemenu2')->name('utility.updateMn2');
	Route::get('utility/deletemenu2/{id}', 'UtilityController@deletemenu2')->name('utility.deleteMn2');

	Route::get('change_pass', 'ChangePasswordController@index')->name('change_pass');
	Route::post('change_pass', 'ChangePasswordController@store')->name('change.password');

	Route::get('assets/clients', 'AssetController@clients')->name('assets.clients');

	Route::get('assets/gallery', 'AssetController@gallery')->name('assets.gallery');
	Route::get('assets/gallery/upload', 'AssetController@newGallery')->name('assets.gallery.upload');
	Route::post('assets/gallery/store', 'AssetController@uploadGallery')->name('assets.gallery.store');
	Route::post('assets/gallery/destroy', 'AssetController@destroyGallery')->name('assets.gallery.destroy');
});

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    protected $table = 'news';

    protected $fillable = ['title','slug','thumbnail','thumbnail_temp','content','categori_id','author','status','tags'];

    function category()
    {
    	return $this->belongsTo(Category::class, 'categori_id');
    }

}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Models\News;
use App\Http\Requests\RequestNews;
use App\Models\Category;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;

class NewsController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth','verified']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.news');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $status = array(
            (object) array('id' => 1, 'name' => 'Publish'),
            (object) array('id' => 2, 'name' => 'Draft'),
            (object) array('id' => 3, 'name' => 'Pending')
        );
        return view('pages.news.create', [
            'news' => new News,
            'categories' => Category::get(),
            'status' => $status
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RequestNews $request)
    {
        $news = new News();
        $news['title'] = $request->txttitle;
        $news['slug'] = Str::slug($request->txttitle);

        $file = $request->file('txtthumbnail');
        $imageName = 'news-'.time().uniqid().'.'.$file->getClientOriginalExtension();
        $file->move(storage_path('app/public/thumbnail'), $imageName);

        $news['thumbnail'] = $imageName;
        $news['thumbnail_temp'] = base64_encode($request->file('txtthumbnail'));
        $news['content'] = $request->txtkonten;
        $news['categori_id'] = $request->txtkategori;
        $news['author'] = $request->txtauthor;
        $news['status'] = $request->txtstatus;
        $news['tags'] = $request->txttags;
        
        $news->save();
        
        return redirect('news/all')->with('success', 'News was Created..!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(News $news)
    {
        $category = Category::get();
        return view('pages.news.show',compact('news','category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(News $news)
    {
        $attr = News::get();
        $categories = Category::get();
        $status = array(
            (object) array('id' => 1, 'name' => 'Publish'),
            (object) array('id' => 2, 'name' => 'Draft'),
            (object) array('id' => 3, 'name' => 'Pending')
        );

        return view('pages.news.edit', compact('news','categories','status'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RequestNews $request, News $news)
    {
        $attr = $request->all();
        $attr['title'] = $request->txttitle;
        $attr['slug'] = Str::slug($request->txttitle);

        if ($request->hasFile('txtthumbnail')) {
        	$request->validate([
        		'txtthumbnail' => 'required|image|mimes:jpeg,jpg,png|max:2048'
        	]);

            $file = $request->file('txtthumbnail');
            if(file_exists(public_path('storage/thumbnail/') . $news->thumbnail)){
                unlink(public_path('storage/thumbnail/') . $news->thumbnail);
            }

            $imageName = 'news-'.time().uniqid().'.'.$file->getClientOriginalExtension();
            $request->txtthumbnail->move(public_path('storage/thumbnail'), $imageName);

        }else{
            $imageName = $news->thumbnail;
        }

        $news['thumbnail'] = $imageName;
        $attr['content'] = $request->txtkonten;
        $attr['categori_id'] = $request->txtkategori;
        $attr['author'] = $request->txtauthor;
        $attr['status'] = $request->txtstatus;
        $attr['tags'] = $request->txttags;
        
        $news->update($attr);
        
        return redirect('news/all')->with('success', 'The News Was Updated..!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(News $news)
    {
        $news->delete();
        return redirect('news/all')->with('success', 'The News was Destroyed..!');
    }

    public function all()
    {
        $title = "All";
        $news = News::get();
        $category = Category::get();
        return view('pages.news.list',compact('news', 'category', 'title'));
    }

    public function published()
    {
        $title = "Published";
        $news = News::where('status','1')->get();
        $category = Category::get();
        return view('pages.news.list',compact('news', 'category', 'title'));
    }

    public function draft()
    {
        $title = "Draft";
        $news = News::where('status','2')->get();
        $category = Category::get();
        return view('pages.news.list',compact('news', 'category', 'title'));
    }

    public function pending()
    {
        $title = "Pending";
        $news = News::where('status','3')->get();
        $category = Category::get();
        return view('pages.news.list',compact('news', 'category', 'title'));
    }
}

resources/views/pages/news/create.blade.php
@extends('layouts.master')
@section('title','News')
@section('content')
<section class="section">
    <div class="section-header">
        <h1>News</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item">News</div>
            <div class="breadcrumb-item">New Entrie</div>
        </div>
    </div>
    <div class="section-body">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4>New News</h4>
                        <div class="card-header-form">
                            <a href="{{ URL::previous() }}" class="btn btn-md btn-info"><i class="fas fa-arrow-left"></i> Back</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('news.store') }}" method="post" enctype="multipart/form-data">
                            @csrf
                            @include('pages.news.partials.form-control', ['submit' => 'Create Post'])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@push('page-scripts')
<script>
    $("select").selectric();
    $(".inputtags").tagsinput('items');
    jQuery(function ($) {
        $(document).ready(function () {
            $(".custom-file-input").on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).siblings(".custom-file-label").addClass("selected").html(fileName);

                var reader = new FileReader();
                reader.onload = function (e) {
                    document.getElementById("preview").src = e.target.result;
                }

                reader.readAsDataURL(this.files[0]);
            });
        });
        CKEDITOR.replace('body_content');
    });
</script>
@endpush

resources/views/pages/news/edit.blade.php
@extends('layouts.master')
@section('title', 'Update Post')
@section('content')
	<section class="section">
		<div class="section-header">
			<h1>Post</h1>
			<div class="section-header-breadcrumb">
				<div class="breadcrumb-item">Post</div>
				<div class="breadcrumb-item">Edit Entrie</div>
			</div>
		</div>
		<div class="section-body">
			<div class="row">
				<div class="col-12 col-md-6 col-lg-12">
					<div class="card">
						<div class="card-header">
							<h4>Edit Post</h4>
							<div class="card-header-form">
								<a href="{{ URL::previous() }}" class="btn btn-md btn-info"><i class="fas fa-arrow-left"></i> Back</a>
							</div>
						</div>
						<div class="card-body">
							<form action="/news/{{ $news->slug }}/edit" method="post" enctype="multipart/form-data">
								@method('patch')
								@csrf
								@include('pages.news.partials.form-control')
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
@endsection

@push('page-scripts')
<script>
  $("select").selectric();
	$(".inputtags").tagsinput('items');

  jQuery(function ($) {
  	$(document).ready(function(){
        $(".custom-file-input").on("change", function() {
          var fileName = $(this).val().split("\\").pop();
          $(this).siblings(".custom-file-label").addClass("selected").html(fileName);

          var reader = new FileReader();
          reader.onload = function(e){
            document.getElementById("preview").src = e.target.result;
          }

          reader.readAsDataURL(this.files[0]);
        });
    });
    CKEDITOR.replace('body_content');
  });
</script>
@endpush

resources/views/pages/news/list.blade.php
@extends('layouts.master')
@section('title','News')
@section('content')
<section class="section">
    <div class="section-header">
        <h1>News</h1>
        <div class="section-header-breadcrumb">
            <a href="{{ route('news.create') }}" class="btn btn-md btn-info" id="modal_menu_level_1"><i class="fas fa-plus"></i> Add News</a>
        </div>
    </div>
    <div class="section-body">
        @if(session('success'))
        <div class="box-body">
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <p style="margin-bottom: 0;"><i class="icon fa fa-check"></i></i> {{ session('success') }}</p>
            </div>
        </div>
        @endif
        @if (count($errors) > 0)
        <div class="box-body">
            <div class="alert alert-danger alert-dismissible">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
        @endif
        <div class="row">
            <div class="col-12 col-md-6 col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4>{{ $title }} News</h4>
                    </div>
                    <div class="card-body">
    					<div class="table-responsive">
    						<table id="list_post" class="table table-striped">
    							<thead>
    								<tr>
    									<th class="text-center pt-2">No</th>
    									<th>Title</th>
    									<th>Category</th>
    									<th>Tags</th>
    									<th>Author</th>
    									<th>Created</th>
    									<th>Status</th>
    								</tr>
    							</thead>
                                <tbody>
                                    @php $no = 1; @endphp
                                    @foreach($news as $row)
                                    <tr>
                                        <td>{{ $no++ }}</td>
                                        <td>
                                            {{ $row->title }}
                                            <div class="table-links">
                                                <a href="{{ route('news.show', ['news' => $row->slug]) }}" class="text-info" title="View Article"><i class="fas fa-eye"></i></a>
                                                <div class="bullet"></div>
                                                <a href="/news/{{ $row->slug }}/edit" class="text-primary" title="Edit Article"><i class="fas fa-pencil-alt"></i></a>
                                            </div>
                                        </td>
                                        <td>
                                            @foreach($category as $ctg)
                                            @if( $ctg->id === $row->categori_id )
                                                {{ $ctg->name }}
                                            @endif
                                            @endforeach
                                        </td>
                                        <td>
                                            @if ($row->tags !== '')
                                            @foreach (explode(',', $row->tags) as $tag)
                                            <span class="badge badge-primary m-1">{{ $tag }}</span>
                                            @endforeach
                                            @endif
                                        </td>
                                        <td>{{ strtoupper($row->author) }}</td>
                                        <td>{{ $row->created_at->diffForHumans() }}</td>
                                        <td>
                                            @if($row->status == '1')
                                                <div class="badge badge-primary">Published</div>
                                            @elseif($row->status == '2')
                                                <div class="badge badge-danger">Draft</div>
                                            @elseif($row->status == '3')
                                                <div class="badge badge-warning">Panding</div>
                                            @endif
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@push('page-scripts')
<script type="text/javascript">
    $('#list_post').dataTable({
        "lengthChange": false,
        "ordering": false,
        "columnDefs": [{
            "className": "dt-center",
            "targets": "_all"
        }]
    });
</script>
@endpush

resources/views/pages/news/show.blade.php
@extends('layouts.master')
@section('title', 'Detail Post')
@section('content')
	<section class="section">
		<div class="section-header">
			<h1>Detail Post</h1>
			<div class="section-header-breadcrumb">
				<div class="breadcrumb-item active"><a href="/posts">Post</a></div>
	            <div class="breadcrumb-item">Detail Post</div>
			</div>
		</div>
		<div class="section-body">
			<h2 class="section-title">{{ $news->title }}</h2>
			<p class="section-lead">
                @foreach($category as $ctg)
                @if( $ctg->id === $news->categori_id )
                    {{ $ctg->name }}
                @endif
                @endforeach
            </p>
			<div class="row">
				<div class="col-12 col-md-6 col-lg-12">
					<div class="card">
						<div class="card-body">
							<img class="img-fluid" src={{asset('storage/thumbnail/'.$news->thumbnail)}}>
							<p class="card-text">
								{!! $news->content !!}
							</p>
							<div>
								Created at {{ $news->created_at->format('d F Y') }}
							</div>
						</div>
						<div class="card-footer d-flex justify-content-between">
              <form action="{{ route('news.destroy', $news->slug) }}" method="post" id="frm">
              	@method('delete')
              	@csrf
              	<input type="hidden" name="txtthumbnail" value="{{asset('storage/thumbnail/'.$news->thumbnail)}}">
                <button type="button" class="btn btn-link text-danger btn-sm" id="btndelete"><i class="fas fa-trash-alt"></i> Delete</button>
              </form>
							<a href="{{ URL::previous() }}" class="btn btn-md btn-info"><i class="fas fa-arrow-left"></i> Back</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
@endsection

@push('page-scripts')
	<script>
		"use strict";

		$('#btndelete').click(function(){
			swal({
                title: 'Are you sure delete this post?',
                text: '{{ $news->title }}',
                icon: 'warning',
                buttons: true,
                dangerMode: true,
		    })
		    .then((willDelete) => {
                if (willDelete) {
                    $('#frm').submit();
		        } else {
                    swal('Your Post is safe!');
		        }
		    });
		});
	</script>
@endpush